### ISSUE TITLE
Apply for Shoman mentorship - mentee

### ISSUE THREAD

**Issue by Nicanor008** [Nicanor008/shoman-FE#24]
As a mentee, I would like to apply to Shoman mentorship. User details to fill in include: 
- full name, 
- email, 
- track, 
- requirement checklist(laptop, internet, time availability for 3 months), 
- goals, 
- previous experience with coding checkbox, 
- goal of taking mentorship, etc.

**Comment by neymarjimoh** [comment]
Will work on this

**Comment by Nicanor008** [comment]
These should be the requirements for backend guys
<img width="713" alt="Screenshot 2020-11-18 at 16 58 50" src="https://user-images.githubusercontent.com/25298492/99539489-5bc40f00-29bf-11eb-9d02-6436a8f0181b.png">

**Comment by neymarjimoh** [comment]
> These should be the requirements for backend guys
> <img alt="Screenshot 2020-11-18 at 16 58 50" width="713" src="https://user-images.githubusercontent.com/25298492/99539489-5bc40f00-29bf-11eb-9d02-6436a8f0181b.png">

Alright ..noted
