### ISSUE TITLE
Teams

### ISSUE THREAD

**Issue by Nicanor008** [Nicanor008/shoman-FE#45]
As a super admin, I want to create teams for users to be learning together and under one mentor.
- [x] Create teams and assign users
- [x] View All teams
- [ ] Edit Team details
- [x] Add or remove user(s)
- [ ] Deactivate team(s), & delete afterwards

As a mentor/mentee, I want to view my teammates/mentees

Relates to issue #23 

## Required Fields
- team name
- mentorId
- menteesId(probably of type array/enum)
- main trackId

**Comment by neymarjimoh** [comment]
working on this
