### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by Nicanor008** [Nicanor008/shoman-FE#9]
- Register user
- login user
- can also introduce OAuth through Facebook/Twitter

**Comment by BaharaJr** [comment]
Hey @Nicanor008 have you started implementing the backend part?

**Comment by Nicanor008** [comment]
Yeah sure, here is the API https://github.com/Ruiru11/Showman-Api.

**Comment by BaharaJr** [comment]
Thank you boss, I wanted to join in the backend team but I see you already pushed further. Congrats

**Comment by Nicanor008** [comment]
Thanks @BaharaJr, you can still join the backend team on Ruiru's Repo, we suppose to do some more stuff but we've been lazy
